#!/bin/sh

set -eu

JFC_CLIENT_SOURCE="${1:-}"
JFC_CLIENT_TARGET="/usr/local/libexec/jfc-e2e-virtual-hid-click"
JFC_SCRIPT_DIR=$(CDPATH='' cd -- "$(/usr/bin/dirname -- "$0")" && /bin/pwd)
JFC_DAEMON_APP="/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app"
JFC_DAEMON_SOURCE="/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon"
JFC_JOB_LABEL="io.e10n.jfc.e2e.virtual-hid"
JFC_JOB_SOURCE="$JFC_SCRIPT_DIR/$JFC_JOB_LABEL.plist"
JFC_JOB_TARGET="/Library/LaunchDaemons/$JFC_JOB_LABEL.plist"
JFC_SUDOERS_TARGET="/etc/sudoers.d/jfc-e2e-virtual-hid"

if [ "$(/usr/bin/id -u)" -ne 0 ]; then
  echo "run this installer with sudo" >&2
  exit 1
fi

JFC_TEST_USER="${SUDO_USER:-}"
case "$JFC_TEST_USER" in
  ''|root|*[!A-Za-z0-9._-]*)
    echo "could not determine a safe non-root test user from SUDO_USER" >&2
    exit 1
    ;;
esac

if [ -z "$JFC_CLIENT_SOURCE" ] || [ ! -f "$JFC_CLIENT_SOURCE" ] \
  || [ ! -x "$JFC_CLIENT_SOURCE" ]; then
  echo "usage: sudo install-privileges.sh <built-click-client>" >&2
  exit 2
fi
if [ ! -x "$JFC_DAEMON_SOURCE" ]; then
  echo "Karabiner VirtualHID daemon not found: $JFC_DAEMON_SOURCE" >&2
  exit 1
fi
if [ ! -f "$JFC_JOB_SOURCE" ]; then
  echo "LaunchDaemon definition not found: $JFC_JOB_SOURCE" >&2
  exit 1
fi

/usr/bin/install -d -o root -g wheel -m 0755 /usr/local/libexec
/usr/bin/install -o root -g wheel -m 0755 "$JFC_CLIENT_SOURCE" "$JFC_CLIENT_TARGET"
/usr/bin/codesign --verify --strict "$JFC_DAEMON_APP"
/usr/bin/plutil -lint "$JFC_JOB_SOURCE"

JFC_CLIENT_SHA=$(/usr/bin/shasum -a 256 "$JFC_CLIENT_TARGET" | /usr/bin/awk '{print $1}')
JFC_LAUNCHCTL_SHA=$(/usr/bin/shasum -a 256 /bin/launchctl | /usr/bin/awk '{print $1}')
JFC_TEMP_SUDOERS=$(/usr/bin/mktemp /private/tmp/jfc-e2e-sudoers.XXXXXX)
trap '/bin/rm -f "$JFC_TEMP_SUDOERS"' EXIT HUP INT TERM

{
  echo "# Generated by JFC E2E/VirtualHIDClick/install-privileges.sh"
  echo "# Reinstall after either authorized executable changes."
  printf '%s ALL=(root) NOPASSWD: sha256:%s %s ""\n' \
    "$JFC_TEST_USER" "$JFC_CLIENT_SHA" "$JFC_CLIENT_TARGET"
  printf '%s ALL=(root) NOPASSWD: sha256:%s %s\n' \
    "$JFC_TEST_USER" "$JFC_LAUNCHCTL_SHA" \
    "/bin/launchctl kickstart system/$JFC_JOB_LABEL"
  printf '%s ALL=(root) NOPASSWD: sha256:%s %s\n' \
    "$JFC_TEST_USER" "$JFC_LAUNCHCTL_SHA" \
    "/bin/launchctl kill SIGTERM system/$JFC_JOB_LABEL"
} > "$JFC_TEMP_SUDOERS"

/bin/chmod 0440 "$JFC_TEMP_SUDOERS"
/usr/sbin/visudo -cf "$JFC_TEMP_SUDOERS"
/bin/rm -f /usr/local/libexec/jfc-e2e-virtual-hid-daemon
if /bin/launchctl print "system/$JFC_JOB_LABEL" >/dev/null 2>&1; then
  /bin/launchctl bootout "system/$JFC_JOB_LABEL"
fi
/usr/bin/install -o root -g wheel -m 0644 "$JFC_JOB_SOURCE" "$JFC_JOB_TARGET"
/bin/launchctl bootstrap system "$JFC_JOB_TARGET"
/usr/bin/install -o root -g wheel -m 0440 "$JFC_TEMP_SUDOERS" "$JFC_SUDOERS_TARGET"
/usr/sbin/visudo -cf /etc/sudoers

echo "installed root-owned click client: $JFC_CLIENT_TARGET"
echo "installed VirtualHID LaunchDaemon: $JFC_JOB_TARGET"
echo "installed checksum-pinned sudo rules: $JFC_SUDOERS_TARGET"
