#!/bin/sh

set -eu

JFC_SCRIPT_DIR=$(CDPATH='' cd -- "$(/usr/bin/dirname -- "$0")" && /bin/pwd)
JFC_HELPER_SOURCE="$JFC_SCRIPT_DIR/install-app.sh"
JFC_HELPER_TARGET="/usr/local/libexec/jfc-e2e-install-app"
JFC_SUDOERS_TARGET="/etc/sudoers.d/jfc-e2e-install-app"

if [ "$(/usr/bin/id -u)" -ne 0 ]; then
  echo "run this installer with sudo" >&2
  exit 1
fi

JFC_TEST_USER="${SUDO_USER:-}"
case "$JFC_TEST_USER" in
  ''|root|*[!A-Za-z0-9._-]*)
    echo "could not determine a safe non-root test user from SUDO_USER" >&2
    exit 1
    ;;
esac

if [ ! -f "$JFC_HELPER_SOURCE" ]; then
  echo "installer helper not found: $JFC_HELPER_SOURCE" >&2
  exit 1
fi

/usr/bin/install -d -o root -g wheel -m 0755 /usr/local/libexec
/usr/bin/install -o root -g wheel -m 0755 "$JFC_HELPER_SOURCE" "$JFC_HELPER_TARGET"

JFC_HELPER_SHA=$(/usr/bin/shasum -a 256 "$JFC_HELPER_TARGET" | /usr/bin/awk '{print $1}')
JFC_TEMP_SUDOERS=$(/usr/bin/mktemp /private/tmp/jfc-e2e-install-sudoers.XXXXXX)
trap '/bin/rm -f "$JFC_TEMP_SUDOERS"' EXIT HUP INT TERM

{
  echo "# Generated by JFC E2E/InstallJFC/install-privileges.sh"
  echo "# Reinstall after the authorized helper changes."
  printf '%s ALL=(root) NOPASSWD: sha256:%s %s install\n' \
    "$JFC_TEST_USER" "$JFC_HELPER_SHA" "$JFC_HELPER_TARGET"
  printf '%s ALL=(root) NOPASSWD: sha256:%s %s uninstall\n' \
    "$JFC_TEST_USER" "$JFC_HELPER_SHA" "$JFC_HELPER_TARGET"
} > "$JFC_TEMP_SUDOERS"

/bin/chmod 0440 "$JFC_TEMP_SUDOERS"
/usr/sbin/visudo -cf "$JFC_TEMP_SUDOERS"
/usr/bin/install -o root -g wheel -m 0440 "$JFC_TEMP_SUDOERS" "$JFC_SUDOERS_TARGET"
/usr/sbin/visudo -cf /etc/sudoers

echo "installed root-owned JFC app installer: $JFC_HELPER_TARGET"
echo "installed checksum-pinned sudo rules: $JFC_SUDOERS_TARGET"
